spring.application.name=library-backend

spring.datasource.url=${DATABASE_URL:jdbc:mysql://mysql-3de9f69a-rohinig693-f290.i.aivencloud.com:24292/defaultdb?sslMode=REQUIRED}
spring.datasource.username=${DATABASE_USERNAME:avnadmin}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}